# name: 13ft Ladder
# about: A small web service that fetches a news article as a search crawler would, to read pages behind soft paywalls.
# docs: https://github.com/wasi-master/13ft#using-docker
# website: https://github.com/wasi-master/13ft
# categories: productivity, rss
# source: musdash
services:
  13ft:
    image: ghcr.io/wasi-master/13ft:latest
    environment:
      - SERVICE_FQDN_13FT_5000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO /dev/null http://127.0.0.1:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
