# name: AllTube
# about: AllTube Download is an application designed to facilitate the downloading of videos from YouTube and other video sites.
# docs: https://github.com/Rudloff/alltube/wiki
# website: https://github.com/Rudloff/alltube
# categories: media
# source: dokploy
services:
  alltube:
    image: dnomd343/alltube:latest
    restart: unless-stopped
    expose:
      - 80
    environment:
      - TITLE=${TITLE:-My AllTube Site}
      - CONVERT=${CONVERT:-true}
      - STREAM=${STREAM:-true}
      - REMUX=${REMUX:-true}
      - SERVICE_FQDN_ALLTUBE_80
