# name: Barrage
# about: Barrage is a minimalistic Deluge WebUI app with full mobile support.
# docs: https://github.com/maulik9898/barrage/blob/main/README.md
# website: https://github.com/maulik9898/barrage
# categories: media
# source: dokploy
services:
  barrage:
    image: maulik9898/barrage:0.3.0
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - NEXTAUTH_SECRET=${SERVICE_BASE64_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://${DOMAIN:-}
      - DELUGE_URL=${DELUGE_URL:-http://your-deluge-ip:8112}
      - DELUGE_PASSWORD=${SERVICE_PASSWORD_DELUGE_PASSWORD}
      - BARRAGE_PASSWORD=${SERVICE_PASSWORD_BARRAGE_PASSWORD}
      - SERVICE_FQDN_BARRAGE_3000
