# name: bolt.diy
# about: Prompt, run, edit, and deploy full-stack web applications using any LLM you want!
# docs: https://stackblitz-labs.github.io/bolt.diy/
# website: https://github.com/stackblitz-labs/bolt.diy
# categories: ai, devtools
# source: dokploy
services:
  app:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY:-}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL:-http://127.0.0.1:11434}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL:-}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG:-}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-info}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
      - SERVICE_FQDN_APP_5173
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: pnpm run dockerstart
