# name: Bytebase
# about: Bytebase is a database management tool that allows you to manage your databases with ease.
# docs: https://www.bytebase.com/docs
# website: https://www.bytebase.com
# categories: database
# source: dokploy
services:
  bytebase:
    image: bytebase/bytebase:3.3.0
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - PG_URL=postgres://postgres:${SERVICE_PASSWORD_DB_PASSWORD}@bytebase-db:5432/bytebase
      - SERVICE_FQDN_BYTEBASE_8080
    volumes:
      - data:/var/opt/bytebase
    depends_on:
      - bytebase-db
  bytebase-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_DB_PASSWORD}
      - POSTGRES_DB=bytebase
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  data:
  db_data:
