# name: changedetection.io
# about: Changedetection.io is an intelligent tool designed to monitor changes on websites.
# docs: https://github.com/dgtlmoon/changedetection.io/wiki
# website: https://changedetection.io/
# categories: monitoring, analytics, communication
# source: dokploy
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.49
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - datastore:/datastore
    environment:
      - SERVICE_FQDN_CHANGEDETECTION_5000
volumes:
  datastore:
