# name: Cockpit
# about: Cockpit is a headless content platform that is lightweight, fast and ready for takeoff.
# docs: https://getcockpit.com/documentation/core/quickstart/installation
# website: https://getcockpit.com/
# categories: cms, backend
# source: coolify
services:
  cockpit:
    image: cockpithq/cockpit:core-latest
    volumes:
      - cockpit-config:/var/www/html/config
      - cockpit-spaces:/var/www/html/.spaces
      - cockpit-storage:/var/www/html/storage
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/api/system/healthcheck"]
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      - SERVICE_FQDN_COCKPIT_80
volumes:
  cockpit-config:
  cockpit-spaces:
  cockpit-storage:
