# name: Dashy
# about: A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more!
# docs: https://dashy.to/docs/quick-start/
# website: https://dashy.to/
# categories: home, monitoring
# source: dokploy
services:
  dashy:
    image: lissy93/dashy:latest
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - dashy-config:/app/user-data
    environment:
      - SERVICE_FQDN_DASHY_8080
volumes:
  dashy-config:
