# name: Deno KV
# about: The Denoland key-value database.
# docs: https://github.com/denoland/denokv#readme
# website: https://deno.com/
# categories: database
# source: coolify
services:
  denokv:
    image: ghcr.io/denoland/denokv:latest
    environment:
      - 'ACCESS_TOKEN=${SERVICE_PASSWORD_DENOKV}'
      - SERVICE_URL_DENOKV_4512
    volumes:
      - denokv-data:/data
    command: '--sqlite-path /data/denokv.sqlite serve --access-token ${SERVICE_PASSWORD_DENOKV}'
    healthcheck:
      test:
        - CMD
        - nc
        - '-zv'
        - 127.0.0.1
        - '4512'
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  denokv-data:
