# name: Double Zero
# about: 00 is a self hostable SES dashboard for sending and monitoring emails with AWS.
# docs: https://github.com/technomancy-dev/00
# categories: email
# source: dokploy
services:
  doublezero:
    restart: always
    image: liltechnomancer/double-zero:0.2.1
    volumes:
      - db-data:/var/lib/doublezero/data
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-your-aws-access-key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-your-aws-secret-key}
      AWS_REGION: ${AWS_REGION:-your-aws-region}
      SQS_URL: ${SQS_URL:-your-aws-sqs-url}
      SYSTEM_EMAIL: ${SYSTEM_EMAIL:-}
      SECRET_KEY_BASE: ${SERVICE_BASE64_64_SECRET_KEY_BASE}
      PHX_HOST: ${SERVICE_FQDN_DOUBLEZERO}
      DATABASE_PATH: ./00.db
      SERVICE_FQDN_DOUBLEZERO_4000:
volumes:
  db-data:
