# name: DumbDrop
# about: DumbDrop is a simple, self-hosted file sharing service with no database or authentication required.
# docs: https://github.com/dumbwareio/dumbdrop
# website: https://dumbware.io/DumbDrop/
# categories: storage
# source: dokploy
services:
  dumbdrop:
    image: dumbwareio/dumbdrop:latest
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - dumbdrop-uploads:/app/uploads
    environment:
      - SERVICE_FQDN_DUMBDROP_3000
volumes:
  dumbdrop-uploads:
