# name: Enshrouded
# about: Enshrouded steam dedicated server.
# docs: https://github.com/mornedhels/enshrouded-server#readme
# website: https://github.com/mornedhels/enshrouded-server
# categories: games
# source: dokploy
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    volumes:
      - enshrouded-persistent-data:/opt/enshrouded
    environment:
      - SERVER_NAME=${SERVER_NAME:-Enshrouded Dokploy}
      - SERVER_PASSWORD=${SERVICE_PASSWORD_SERVER_PASSWORD}
      - SERVER_SLOT_COUNT=6
      - UPDATE_CRON=0 3 * * *
      - PUID=4711
      - PGID=4711
    ports:
      - "15637:15637/udp"
      - "37015:27015/udp"
volumes:
  enshrouded-persistent-data:
