# name: Excalidraw
# about: Virtual whiteboard for sketching hand-drawn like diagrams.
# docs: https://docs.excalidraw.com/docs
# website: https://excalidraw.com/
# categories: productivity, devtools, docs
# source: coolify
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    environment:
      - SERVICE_URL_EXCALIDRAW_80
    healthcheck:
      test:
        - CMD
        - wget
        - '--spider'
        - '--quiet'
        - 'http://localhost'
      interval: 10s
      timeout: 5s
      retries: 10
