# name: FlareSolverr
# about: FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.
# docs: https://github.com/FlareSolverr/FlareSolverr
# categories: networking
# source: dokploy
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    expose:
      - 8191
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_FLARESOLVERR_8191
