# name: FreshRSS
# about: A free, self-hostable feed aggregator.
# docs: https://github.com/FreshRSS/FreshRSS/tree/edge/Docker
# website: https://freshrss.org/
# categories: rss
# source: coolify
services:
  freshrss:
    image: freshrss/freshrss:latest
    environment:
      - SERVICE_URL_FRESHRSS_80
      - CRON_MIN=${CRON_MIN:-1,31}
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 3
volumes:
  freshrss-data:
  freshrss-extensions:
