# name: Gel
# about: Gel is a next-generation graph-relational database (formerly EdgeDB) with a built-in migration system, expressive query language, and first-class…
# docs: https://docs.geldata.com/
# website: https://www.geldata.com/
# categories: database
# source: dokploy
services:
  gel:
    image: geldata/gel:6
    restart: unless-stopped
    expose:
      - 5656
    environment:
      - GEL_SERVER_SECURITY=${GEL_SERVER_SECURITY:-strict}
      - GEL_SERVER_PASSWORD=${SERVICE_PASSWORD_GEL_PASSWORD}
      - GEL_SERVER_TLS_CERT_MODE=generate_self_signed
      - GEL_SERVER_HTTP_ENDPOINT_SECURITY=optional
      - GEL_SERVER_ADMIN_UI=enabled
      - SERVICE_FQDN_GEL_5656
    volumes:
      - gel-data:/var/lib/gel/data
volumes:
  gel-data:
