# name: LibreOffice
# about: LibreOffice is a free and powerful office suite.
# docs: https://docs.linuxserver.io/images/docker-libreoffice/
# website: https://www.libreoffice.org/
# categories: productivity, docs
# source: coolify
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    environment:
      - SERVICE_URL_LIBREOFFICE_3000
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - libreoffice-config:/config
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  libreoffice-config:
