# name: Lodestone
# about: A free, open source server hosting tool for Minecraft and other multiplayers games.
# docs: https://github.com/Lodestone-Team/lodestone/wiki
# website: https://lodestone.cc
# categories: games
# source: dokploy
services:
  lodestone:
    image: ghcr.io/lodestone-team/lodestone_core:latest
    volumes:
      - lodestone:/home/user/.lodestone
    restart: unless-stopped
    ports:
      - "16662:16662"
      - "35565-35590:25565-25590"
  lodestone_dashboard:
    image: ghcr.io/lodestone-team/lodestone_dashboard:v0.5.1
    restart: always
    environment:
      - SERVICE_FQDN_LODESTONE_DASHBOARD_80
volumes:
  lodestone:
