# name: Memos
# about: An open-source, lightweight note-taking solution. The pain-less way to create your meaningful notes. Your Notes, Your Way.
# docs: https://github.com/usememos/memos
# categories: productivity, docs, communication
# source: coolify
services:
  memos:
    image: neosmemo/memos:stable
    volumes:
      - memos-memos:/var/opt/memos
    environment:
      - SERVICE_URL_MEMOS_5230
volumes:
  memos-memos:
