# name: Overseerr
# about: Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
# docs: https://docs.overseerr.dev/getting-started/installation#docker
# categories: media
# source: coolify
services:
  overseerr:
    image: sctx/overseerr:latest
    environment:
      - SERVICE_URL_OVERSEERR_5055
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Toronto}
    volumes:
      - overseerr-config:/app/config
    healthcheck:
      test: ["CMD", "wget", "--tries", "1", "--no-verbose", "--spider", "http://localhost:5055/api/v1/status"]
      interval: 2s
      timeout: 10s
      retries: 15
volumes:
  overseerr-config:
