# name: PrivateBin
# about: PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data.
# docs: https://github.com/PrivateBin/docker-nginx-fpm-alpine#readme
# website: https://privatebin.info/
# categories: security, storage
# source: coolify
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    environment:
      - SERVICE_URL_PRIVATEBIN_8080
    volumes:
      - privatebin_data:/srv/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/"]
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  privatebin_data:
