# name: Rivet Engine
# about: Build and scale stateful workloads with long-lived processes.
# docs: https://rivet.dev/docs/deploy/self-host/control-plane/docker-compose/
# website: https://rivet.dev/
# categories: devtools, backend
# source: coolify
services:
  rivet-engine:
    image: rivetdev/engine:2.2.0
    environment:
      - SERVICE_URL_RIVET_6420
      - RIVET__FILE_SYSTEM__PATH=/data
      - 'RIVET__AUTH__ADMIN_TOKEN=${SERVICE_PASSWORD_TOKEN}'
    volumes:
      - 'rivet-data:/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://127.0.0.1:6420/health
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
volumes:
  rivet-data:
