# name: RSS-Bridge
# about: RSS-Bridge is a PHP project capable of generating Atom feeds for websites that don't have one.
# docs: https://rss-bridge.github.io/rss-bridge/For_Hosts/Installation.html
# website: https://rss-bridge.github.io/rss-bridge/
# categories: rss, cms
# source: dokploy
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - rssbridge-config:/config
    environment:
      - SERVICE_FQDN_RSS_BRIDGE_80
volumes:
  rssbridge-config:
