# name: Shlink
# about: The definitive self-hosted URL shortener.
# docs: https://shlink.io/documentation/install-docker-image/
# website: https://shlink.io/
# categories: productivity, business, storage
# source: coolify
services:
  shlink:
    image: shlinkio/shlink:stable
    environment:
      - SERVICE_URL_SHLINK_8080
      - DEFAULT_DOMAIN=${SERVICE_FQDN_SHLINK}
      - IS_HTTPS_ENABLED=false
      - INITIAL_API_KEY=${SERVICE_PASSWORD_SHLINKAPIKEY}
    volumes:
      - shlink-data:/etc/shlink/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/rest/v3/health"]
      interval: 2s
      timeout: 10s
      retries: 15
  shlink-web:
    image: shlinkio/shlink-web-client:latest
    environment:
      - SERVICE_URL_SHLINKWEB_8080
      - SHLINK_SERVER_API_KEY=${SERVICE_PASSWORD_SHLINKAPIKEY}
      - SHLINK_SERVER_URL=${SERVICE_URL_SHLINK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 2s
      timeout: 10s
      retries: 15
volumes:
  shlink-data:
