# name: Statusnook
# about: Effortlessly deploy a status page and start monitoring endpoints in minutes.
# docs: https://statusnook.com
# categories: monitoring
# source: coolify
services:
  statusnook:
    environment:
      - SERVICE_URL_STATUSNOOK_8000
    volumes:
      - "statusnook-data:/app/statusnook-data"
    image: goksan/statusnook:latest
    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "--spider"
        - "http://127.0.0.1:8000"
      interval: 2s
      timeout: 10s
      retries: 15
volumes:
  statusnook-data:
