# name: TriliumNext
# about: Build your personal knowledge base with TriliumNext Notes.
# docs: https://github.com/TriliumNext/Trilium
# categories: productivity, docs
# source: coolify
services:
  triliumnext:
    image: ghcr.io/triliumnext/trilium:stable
    environment:
      - SERVICE_URL_TRILIUMNEXT_8080
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - triliumnext_data:/home/node/trilium-data
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/docker_healthcheck.cjs"]
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  triliumnext_data:
