# name: Vvveb
# about: Powerful and easy to use cms to build websites, blogs or ecommerce stores.
# docs: https://docs.vvveb.com
# categories: cms, ecommerce, backend
# source: coolify
services:
  vvveb:
    image: vvveb/vvvebcms:latest
    volumes:
      - vvveb-data:/var/www/html
    environment:
      - SERVICE_URL_VVVEB_80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
volumes:
  vvveb-data:
