# name: yt-dlp-webui
# about: yt-dlp-webui is a web interface for yt-dlp, allowing you to download videos and audio from various platforms with a simple web UI.
# docs: https://github.com/marcopiovanello/yt-dlp-web-ui
# categories: media
# source: dokploy
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui:latest
    expose:
      - 3033
    volumes:
      - downloads:/downloads
      - config:/config
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_YT_DLP_WEBUI_3033
volumes:
  downloads:
  config:
