"""Build docs/testing/vps-test-report.md from out/results.jsonl + findings.md (hand-written)."""
import json, re, collections, datetime, os
latest = collections.OrderedDict()
for line in open("out/results.jsonl"):
    try: r = json.loads(line)
    except Exception: continue
    latest[r["case"]] = r
NAMES = {0: "Install and baseline", 1: "First run, sign-in, sessions, headers", 2: "Account: profile, password, two-step, API tokens", 3: "Team, roles, invitations",
         4: "Projects and environments", 5: "Image apps and deployments", 6: "Domains, TLS and the proxy", 7: "Git deploys", 8: "Databases", 9: "Backups and storage",
         10: "Services (Docker Compose)", 11: "Operations: tasks, notifications", 12: "Servers, metrics, multi-server", 13: "Shared variables and tags", 14: "API",
         15: "Terminal", 16: "Security probes", 17: "Resilience and resource budget", 18: "UI sweep (browser)"}
def suite(c):
    m = re.match(r"S(\d+)", c); return int(m.group(1)) if m else 99
by = collections.defaultdict(list)
for c, r in latest.items(): by[suite(c)].append((c, r))
tot = collections.Counter(r["status"] for r in latest.values())
out = []
w = out.append
w("<!-- generated by test/vps/make_report.py from out/results.jsonl; the Findings section is written by hand in test/vps/findings.md -->\n")
out_head = open("report_head.md").read() if os.path.exists("report_head.md") else ""
w(out_head)
w("\n## Results by suite\n")
w("| Suite | Pass | Fail | Blocked | Info |\n|---|---:|---:|---:|---:|")
for s in sorted(by):
    cnt = collections.Counter(r["status"] for _, r in by[s])
    w(f"| S{s} {NAMES.get(s, '')} | {cnt['PASS']} | {cnt['FAIL']} | {cnt['BLOCKED']} | {cnt['INFO']} |")
w(f"| **Total** | **{tot['PASS']}** | **{tot['FAIL']}** | **{tot['BLOCKED']}** | **{tot['INFO']}** |\n")
if os.path.exists("findings.md"): w(open("findings.md").read())
w("\n## Every recorded case\n")
w("Status: ok = behaved as documented, FAIL = defect, BLOCKED = not testable here, info = observation. The last record for a case wins.\n")
for s in sorted(by):
    w(f"\n### S{s} {NAMES.get(s, '')}\n")
    w("| Case | Result | What was checked / seen |\n|---|---|---|")
    for c, r in sorted(by[s], key=lambda x: [(0, int(p), "") if p.isdigit() else (1, 0, p) for p in re.findall(r"\d+|[A-Za-z]+", x[0][1:])]):
        note = re.sub(r"(musdash_(?:session|csrf|2fa)=)[A-Za-z0-9_\-]+", r"\1<redacted>", re.sub(r"\b(?:msd|mdt)_[A-Za-z0-9_\-]{10,}", "<token>", r["note"])).replace("|", "\\|").replace("\n", " ")[:420]
        st = {"PASS": "ok", "FAIL": "**FAIL" + (f" {r['sev']}" if r["sev"] else "") + "**", "BLOCKED": "blocked", "INFO": "info", "NA": "n/a"}[r["status"]]
        w(f"| {c} | {st} | {note} |")
open("../../docs/testing/vps-test-report.md", "w").write("\n".join(out) + "\n")
print("written", len(latest), "cases")
