package deploy

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"path"
	"sort"
	"strings"
	"time"

	"github.com/MahmoudDahdouh/musdash-go/internal/db"
	"github.com/MahmoudDahdouh/musdash-go/internal/docker"
	"github.com/MahmoudDahdouh/musdash-go/internal/runner"
)

// Build packs that need no Dockerfile: a builder reads the repository and
// works out how to build it.
//
// A builder is a program from somewhere else that reads files somebody
// else wrote. It is never installed on a server. It runs in a container
// made from an image musdash builds the first time it is needed, and that
// container can see the checkout and nothing else of the server: no Docker
// socket, no capabilities, a read-only root. What comes out of it is a
// plan; the image itself is built by `docker build`, as for a Dockerfile.
const (
	PackNixpacks = "nixpacks"
	PackRailpack = "railpack"
)

// ValidPack reports whether name is a build pack.
func ValidPack(name string) bool {
	switch name {
	case PackDockerfile, PackStatic, PackNixpacks, PackRailpack:
		return true
	}
	return false
}

// ListensOnPORT reports whether apps built with a pack read the port to
// listen on from the PORT variable, as both builders arrange.
func ListensOnPORT(pack string) bool { return pack == PackNixpacks || pack == PackRailpack }

// builder is one of the tools: where its release is, and what the file of
// each architecture must hash to. A build must not change because a
// release file was replaced.
type builder struct {
	name    string // also the name of its command
	label   string
	version string
	// file is the release file's address with %s for the architecture as
	// the project names it.
	file   string
	assets map[string]asset // Docker's architecture name → the file
}

type asset struct {
	arch string // as it appears in the file name
	sum  string // SHA-256 of the file
}

// The releases in use. The checksums of Railpack's files are the ones it
// publishes; Nixpacks publishes none, and those are of the files as they
// were on 2026-10-05.
var builders = map[string]builder{
	PackNixpacks: {
		name: "nixpacks", label: "Nixpacks", version: "1.41.0",
		file: "https://github.com/railwayapp/nixpacks/releases/download/v1.41.0/nixpacks-v1.41.0-%s-unknown-linux-musl.tar.gz",
		assets: map[string]asset{
			"amd64": {"x86_64", "0f55de7874507b9cf7502113120bd96f2ab6979f78d10eaf2eb2ade9207b3af6"},
			"arm64": {"aarch64", "912bd02dd2bb6f9c3a9ed965fe8a68b4aa318dc7a2546e2eca6f2806a894ba39"},
		},
	},
	PackRailpack: {
		name: "railpack", label: "Railpack", version: "0.40.1",
		file: "https://github.com/railwayapp/railpack/releases/download/v0.40.1/railpack-v0.40.1-%s-unknown-linux-musl.tar.gz",
		assets: map[string]asset{
			"amd64": {"x86_64", "2842de93e68713af9037e0bc0a398d7da78f3b96aa4804303a638db2bc69bd30"},
			"arm64": {"arm64", "c24a064b586b8f4f8c2fab44dd5ef19253e4c6cc4e1df793b3ae19cd87f7a5d4"},
		},
	},
}

// railpackFrontend is the BuildKit frontend that turns a Railpack plan
// into an image. It is the same release as the command that wrote the plan.
func railpackFrontend() string {
	return "ghcr.io/railwayapp/railpack-frontend:v" + builders[PackRailpack].version
}

// image is the local image the builder runs from.
func (b builder) image() string { return "musdash/" + b.name + ":" + b.version }

// dockerfile is what the builder's image is made from: the release file,
// fetched by Docker and refused unless it is the file that was pinned.
func (b builder) dockerfile(arch string) (string, error) {
	a, ok := b.assets[arch]
	if !ok {
		return "", fmt.Errorf("%s has no release for this server's architecture (%s)", b.label, clip(arch, 20))
	}
	return "# Generated by musdash: the " + b.label + " command line, which plans builds.\n" +
		"FROM alpine:3\n" +
		"ADD --checksum=sha256:" + a.sum + " " + fmt.Sprintf(b.file, a.arch) + " /tmp/tool.tar.gz\n" +
		"RUN mkdir /tmp/x && tar -xzf /tmp/tool.tar.gz -C /tmp/x && mv /tmp/x/" + b.name + " /usr/local/bin/" + b.name +
		" && chmod 0755 /usr/local/bin/" + b.name + " && rm -rf /tmp/x /tmp/tool.tar.gz\n", nil
}

// planTimeout bounds one step of planning: making the builder's image, or
// one run of the builder. The first use on a server fetches a base image
// and the release.
const planTimeout = 10 * time.Minute

// ensureBuilder makes the builder's image on the server unless it is there.
func (d *Deployer) ensureBuilder(ctx context.Context, r runner.Runner, b builder, log *Log) error {
	dk := docker.Client{R: r}
	if have, err := dk.HasImage(ctx, b.image()); err != nil {
		return err
	} else if have {
		return nil
	}
	out, err := r.Output(ctx, runner.Cmd{Name: "docker", Args: []string{"version", "--format", "{{.Server.Arch}}"}})
	if err != nil {
		return fmt.Errorf("ask Docker for the server's architecture: %w", err)
	}
	// The answer picks one of the known files or none: it never becomes
	// part of an address.
	text, err := b.dockerfile(strings.TrimSpace(string(out)))
	if err != nil {
		return err
	}
	log.Step("Setting up %s %s on this server (once)", b.label, b.version)
	ctx, cancel := context.WithTimeout(ctx, planTimeout)
	defer cancel()
	err = dk.Build(ctx, docker.BuildSpec{Tag: b.image(), Dockerfile: "Dockerfile", Context: docker.DockerfileContext(text)}, log)
	if err != nil {
		return fmt.Errorf("set up %s (it needs Docker 24 or newer, and the server must reach github.com): %w", b.label, err)
	}
	return nil
}

// sandbox describes one run of a builder.
type sandbox struct {
	image   string
	user    string // "uid:gid" of whoever owns the checkout
	envFile string // the app's build variables, read by docker's command line
	src     string // the directory to plan, shown at /src
	// writable lets the builder write into src: Nixpacks leaves its
	// Dockerfile next to the app, in a checkout that is thrown away.
	writable bool
	// network lets the builder reach the network. Railpack asks which
	// versions of a language exist; Nixpacks asks nothing.
	network bool
}

// cmd is `docker run` for a builder with the given command.
func (s sandbox) cmd(argv ...string) (runner.Cmd, error) {
	if !docker.ValidImage(s.image) || !docker.ValidMountPath(s.src) || !docker.ValidMountPath(s.envFile) || s.user == "" {
		return runner.Cmd{}, fmt.Errorf("builder: bad image, directory or variables file")
	}
	args := []string{
		"run", "--rm",
		"--read-only",
		"--cap-drop", "ALL",
		"--security-opt", "no-new-privileges",
		// A repository written to make the builder work hard gets little
		// to do it with.
		"--memory", "1g",
		"--pids-limit", "256",
		"--user", s.user,
		"--workdir", "/tmp",
		"--env-file", s.envFile,
		// After the variables file, so that a variable of the same name
		// cannot move the builder's own files.
		"--env", "HOME=/tmp",
	}
	if s.network {
		// Railpack fetches the tool it resolves versions with and runs it
		// from its home.
		args = append(args, "--tmpfs", "/tmp:rw,exec,nosuid,size=512m")
	} else {
		args = append(args, "--network", "none", "--tmpfs", "/tmp")
	}
	mount := "type=bind,source=" + s.src + ",target=/src"
	if !s.writable {
		mount += ",readonly"
	}
	args = append(args, "--mount", mount, s.image)
	return runner.Cmd{Name: "docker", Args: append(args, argv...)}, nil
}

// envFlags names the app's build variables to a builder. Only the names
// are on the command line: the values are in the container's environment.
func envFlags(vars map[string]string) []string {
	names := make([]string, 0, len(vars))
	for name := range vars {
		names = append(names, name)
	}
	sort.Strings(names)
	flags := make([]string, 0, 2*len(names))
	for _, name := range names {
		flags = append(flags, "--env", name)
	}
	return flags
}

// prepareSandbox makes the builder's image and writes the variables file.
func (d *Deployer) prepareSandbox(ctx context.Context, r runner.Runner, b builder, workDir, src string, vars map[string]string, log *Log) (sandbox, error) {
	if err := d.ensureBuilder(ctx, r, b, log); err != nil {
		return sandbox{}, err
	}
	list := make([]db.EnvVar, 0, len(vars))
	for name, value := range vars {
		list = append(list, db.EnvVar{Key: name, Value: value})
	}
	sort.Slice(list, func(i, j int) bool { return list[i].Key < list[j].Key })
	body, err := EnvFile(list)
	if err != nil {
		return sandbox{}, err
	}
	envFile := path.Join(workDir, "builder.env")
	if err := r.WriteFile(ctx, envFile, 0o600, strings.NewReader(body)); err != nil {
		return sandbox{}, err
	}
	return sandbox{image: b.image(), user: sandboxUser(ctx, r), envFile: envFile, src: src}, nil
}

// builderError words a builder's failure with what it printed.
func builderError(b builder, err error) error {
	var exit *runner.ExitError
	if errors.As(err, &exit) && strings.TrimSpace(exit.Stderr) != "" {
		lines := strings.Split(strings.TrimSpace(exit.Stderr), "\n")
		if len(lines) > 8 {
			lines = lines[len(lines)-8:]
		}
		return fmt.Errorf("%s could not plan the build: %s", b.label, clip(strings.Join(lines, " "), 600))
	}
	return fmt.Errorf("%s: %w", b.label, err)
}

// maxPlanVars is how many variables of a plan are passed on.
const maxPlanVars = 200

// planNixpacks has Nixpacks write a Dockerfile for the app and fills in
// spec to build it.
//
// Nixpacks runs twice: once to say which variables the build takes, and
// once to write `.nixpacks/Dockerfile` next to the app. The Dockerfile
// declares those variables as build arguments without values, so the
// values have to come from here.
func (d *Deployer) planNixpacks(ctx context.Context, r runner.Runner, app db.App, checkout, workDir string, spec *docker.BuildSpec, log *Log) error {
	b := builders[PackNixpacks]
	// The Dockerfile is read from the checkout by path. A repository whose
	// ".nixpacks" is a link would have it read from wherever that points.
	for _, rel := range []string{".nixpacks", ".nixpacks/Dockerfile"} {
		if err := d.refuseSymlinks(ctx, r, checkout, joinRel(app.BaseDir, rel)); err != nil {
			return err
		}
	}
	box, err := d.prepareSandbox(ctx, r, b, workDir, spec.ContextDir, spec.BuildArgs, log)
	if err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(ctx, planTimeout)
	defer cancel()

	log.Step("Planning the build with %s %s", b.label, b.version)
	flags := envFlags(spec.BuildArgs)
	plan, err := box.cmd(append([]string{"nixpacks", "plan", "/src", "--format", "json"}, flags...)...)
	if err != nil {
		return err
	}
	out, err := r.Output(ctx, plan)
	if err != nil {
		return builderError(b, err)
	}
	var doc struct {
		Variables map[string]any `json:"variables"`
	}
	if err := json.Unmarshal(out, &doc); err != nil {
		return fmt.Errorf("%s printed a plan that cannot be read", b.label)
	}
	if len(doc.Variables) > maxPlanVars {
		return fmt.Errorf("the %s plan names %d variables; at most %d are passed to a build", b.label, len(doc.Variables), maxPlanVars)
	}
	// The app's own variables go the way they always do. What else the
	// plan names comes from Nixpacks or from the repository's
	// nixpacks.toml, and is passed with its value: it is not secret, and
	// its name is not one the docker command may be handed as its own
	// environment.
	plain := make(map[string]string)
	for name, value := range doc.Variables {
		if _, own := spec.BuildArgs[name]; own {
			continue
		}
		if text, ok := value.(string); ok {
			plain[name] = text
		}
	}

	box.writable = true
	write, err := box.cmd(append([]string{"nixpacks", "build", "/src", "--out", "/src"}, flags...)...)
	if err != nil {
		return err
	}
	write.Stdout, write.Stderr = log, log
	if err := r.Run(ctx, write); err != nil {
		return fmt.Errorf("%s could not plan the build: %w", b.label, err)
	}
	// What was written is checked where it will be read: on the server,
	// not inside the container that wrote it.
	generated := path.Join(spec.ContextDir, ".nixpacks")
	const plainFile = `test ! -L "$1" && test ! -L "$1/Dockerfile" && test -f "$1/Dockerfile"`
	if _, err := r.Output(ctx, runner.Cmd{Name: "sh", Args: []string{"-c", plainFile, "sh", generated}}); err != nil {
		return fmt.Errorf("%s did not leave a Dockerfile to build from", b.label)
	}
	spec.Dockerfile = path.Join(generated, "Dockerfile")
	spec.PlainArgs = plain
	return nil
}

// railpackPrepare prints the plan after Railpack's own summary, which goes
// to the deployment's log.
const railpackPrepare = `railpack prepare /src --plan-out /tmp/plan.json --info-out /tmp/info.json "$@" >&2 && cat /tmp/plan.json`

// planRailpack has Railpack write a build plan for the app and fills in
// spec to build it with Railpack's BuildKit frontend. The app's build
// variables reach the build as secrets: the plan names them, and the
// frontend gives them to the build's commands without writing them into
// the image.
func (d *Deployer) planRailpack(ctx context.Context, r runner.Runner, app db.App, workDir string, spec *docker.BuildSpec, log *Log) error {
	b := builders[PackRailpack]
	box, err := d.prepareSandbox(ctx, r, b, workDir, spec.ContextDir, spec.BuildArgs, log)
	if err != nil {
		return err
	}
	box.network = true
	ctx, cancel := context.WithTimeout(ctx, planTimeout)
	defer cancel()

	log.Step("Planning the build with %s %s", b.label, b.version)
	prepare, err := box.cmd(append([]string{"sh", "-c", railpackPrepare, "sh"}, envFlags(spec.BuildArgs)...)...)
	if err != nil {
		return err
	}
	prepare.Stderr = log
	out, err := r.Output(ctx, prepare)
	if err != nil {
		return builderError(b, err)
	}
	plan := strings.TrimSpace(string(out))
	if !strings.HasPrefix(plan, "{") || !json.Valid([]byte(plan)) {
		return fmt.Errorf("%s printed a plan that cannot be read", b.label)
	}
	planFile := path.Join(workDir, "railpack-plan.json")
	if err := r.WriteFile(ctx, planFile, 0o600, strings.NewReader(plan)); err != nil {
		return err
	}
	spec.Dockerfile = planFile
	spec.Frontend = railpackFrontend()
	spec.Secrets, spec.BuildArgs = spec.BuildArgs, nil
	spec.FrontendArgs = map[string]string{
		// Build caches are kept per app, and a changed secret is a
		// changed build.
		"cache-key":    app.ID,
		"secrets-hash": secretsHash(spec.Secrets),
	}
	return nil
}

// secretsHash changes when any build variable's name or value does.
func secretsHash(vars map[string]string) string {
	names := make([]string, 0, len(vars))
	for name := range vars {
		names = append(names, name)
	}
	sort.Strings(names)
	h := sha256.New()
	for _, name := range names {
		fmt.Fprintf(h, "%d:%s=%d:%s\n", len(name), name, len(vars[name]), vars[name])
	}
	return hex.EncodeToString(h.Sum(nil))
}
